# Generated by Django 3.1.1 on 2020-09-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0004_auto_20200904_1400'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchhistory',
            options={'ordering': ['team1', 'team2']},
        ),
        migrations.RenameField(
            model_name='matchhistory',
            old_name='home_team',
            new_name='team1',
        ),
        migrations.RenameField(
            model_name='matchhistory',
            old_name='away_team',
            new_name='team2',
        ),
        migrations.CreateModel(
            name='NeutralStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.PositiveSmallIntegerField(default=0)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('loss', models.PositiveSmallIntegerField(default=0)),
                ('no_result', models.PositiveSmallIntegerField(default=0)),
                ('win_pct', models.PositiveSmallIntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nteam1', to='ipl_app.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nteam2', to='ipl_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='HomeStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.PositiveSmallIntegerField(default=0)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('loss', models.PositiveSmallIntegerField(default=0)),
                ('no_result', models.PositiveSmallIntegerField(default=0)),
                ('win_pct', models.PositiveSmallIntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hteam1', to='ipl_app.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hteam2', to='ipl_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='AwayStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.PositiveSmallIntegerField(default=0)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('loss', models.PositiveSmallIntegerField(default=0)),
                ('no_result', models.PositiveSmallIntegerField(default=0)),
                ('win_pct', models.PositiveSmallIntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ateam1', to='ipl_app.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ateam2', to='ipl_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='AllStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.PositiveSmallIntegerField(default=0)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('loss', models.PositiveSmallIntegerField(default=0)),
                ('no_result', models.PositiveSmallIntegerField(default=0)),
                ('win_pct', models.PositiveSmallIntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='ipl_app.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='ipl_app.team')),
            ],
        ),
    ]
