# Generated by Django 3.1.1 on 2020-09-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0004_auto_20200904_1400'),
        ('staff', '0002_auto_20200905_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstats',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='ipl_app.team'),
        ),
        migrations.AlterField(
            model_name='awaystats',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ateam2', to='ipl_app.team'),
        ),
        migrations.AlterField(
            model_name='homestats',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hteam2', to='ipl_app.team'),
        ),
        migrations.AlterField(
            model_name='neutralstats',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nteam2', to='ipl_app.team'),
        ),
    ]
