# Generated by Django 3.1.1 on 2020-09-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200906_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allstats',
            options={'ordering': ['team1', 'team2']},
        ),
        migrations.AlterModelOptions(
            name='awaystats',
            options={'ordering': ['team1', 'team2']},
        ),
        migrations.AlterModelOptions(
            name='homestats',
            options={'ordering': ['team1', 'team2']},
        ),
        migrations.AlterModelOptions(
            name='matchhistory',
            options={'ordering': ['team1', 'team2', 'date']},
        ),
        migrations.AlterModelOptions(
            name='neutralstats',
            options={'ordering': ['team1', 'team2']},
        ),
    ]
