# Generated by Django 3.1.1 on 2020-09-03 09:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_choices', models.CharField(default='20,40,50,70,90,100', max_length=20, validators=[django.core.validators.int_list_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CSK', 'Chennai Super Kings'), ('DC', 'Delhi Capitals'), ('KXIP', 'Kings XI Punjab'), ('KKR', 'Kolkata Knightriders'), ('MI', 'Mumbai Indians'), ('RR', 'Rajasthan Royals'), ('RCB', 'Royal Challengers Bangalore'), ('SRH', 'Sunrisers Hyderabad')], max_length=4, unique=True)),
                ('back_color', models.CharField(max_length=7)),
                ('fore_color', models.CharField(max_length=7)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('P', 'Completed'), ('N', 'Scheduled'), ('A', 'Abandoned')], default='N', max_length=1)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='ipl_app.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='ipl_app.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win', to='ipl_app.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
