# Generated by Django 3.1.1 on 2020-09-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0002_auto_20200903_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_amt',
            field=models.PositiveSmallIntegerField(choices=[(20, '20'), (40, '40'), (60, '60'), (80, '80'), (100, '100')], default=20),
        ),
    ]
