# Generated by Django 3.1.1 on 2020-09-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0003_auto_20200903_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='i_height',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='team',
            name='i_width',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
