# Generated by Django 3.1.1 on 2020-09-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0004_auto_20200904_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_win_pct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_win_pct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
