# Generated by Django 3.1.1 on 2020-09-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0010_auto_20200908_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
