# Generated by Django 3.1.1 on 2020-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0013_auto_20200909_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_amt',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
