# Generated by Django 3.1.1 on 2020-10-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0015_static_team_chg_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='static',
            name='row',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
