# Generated by Django 3.1.1 on 2020-09-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bets_lost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='bets_won',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
